name: MLOPs - Student Exam Results Framework

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r student_exam_results/requirements.txt
    - name: Run tests
      run: |
        source venv/bin/activate
        pytest --junitxml=reports/test-results.xml
